version: "3"
services:
  # common
  lbs_db:
    container_name: lbs_db
    image: 'mariadb:latest'
    env_file: ./services/.env
    volumes:
      - "./docker/db:/var/lib/mysql"
      - "./docker/sql:/docker-entrypoint-initdb.d/"
    networks:
      - lbs
  lbs_adminer:
    container_name: lbs_adminer
    image: 'adminer'
    env_file: ./services/.env
    ports:
      - 8080:8080
    depends_on:
      - lbs_db
    networks:
      - lbs

  # commandes
  lbs_commandes:
    container_name: lbs_commandes
    image: 'node:lts'
    env_file: ./services/.env
    working_dir: /usr/src/app
    volumes:
      - './services/commandes:/usr/src/app'
    ports:
      - '3333:3000'
    command: yarn dev
    depends_on:
      - lbs_db
    networks:
      - lbs
networks:
  lbs:
    driver: bridge
